### ISSUE TITLE
Ensure sentry passes JS integration tests and benchmarks

### ISSUE THREAD

**Issue by Ivshti** [AmbireTech/adex-validator-stack-rust#257]
ensure both pass

please report the results of the benchmark here, the release mode benchmark of the sentry should be at least a few times better

@samparsky @elpiel you can split duties between the benchmark suite and the integration tests

**Comment by elpiel** [comment]
I can confirm that @samparsky made the integration tests run and pass! Now I am looking at the benchmark and @samparsky is looking into the failing routes tests

**Comment by elpiel** [comment]
I am debugging sentry to see why we have such a low `req/sec` from the benchmark.

**Comment by elpiel** [comment]
I am changing the priority of this task since the Rust Sentry is lacking behind the JS one and we need to make sure all integration tests are passing.

Currently known issues to catch up with JS Sentry are:
- [x] #335  impled in PR #352 
- [x] #338 
- [x] #319 

@simzzz Please double check if additional routes, features, etc are still missing from the Rust Sentry implementation and share them in order to be able to prioritize and track them

**Comment by elpiel** [comment]
V5 & #377 have introduced both the `test_harness` and additional tests for both sentry & worker and benchmarks for sentry (events submission)
