### ISSUE TITLE
use TLS to listen to HTTPS

### ISSUE THREAD

**Issue by Ivshti** [AmbireTech/adex-validator-stack-rust#32]
see `rustls`, `tokio_rustls` in https://github.com/cong-lian/playground/blob/master/tls_server_v2/src/main.rs as an example

**Comment by elpiel** [comment]
For our current pure `hyper` server there's a small crate that allows TLS setup of the server:

https://github.com/matszpk/simple-hyper-server-tls

Related to `actix-web`, here's the example for the framework:

https://github.com/actix/examples/blob/master/https-tls/rustls/src/main.rs

**Comment by elpiel** [comment]
After #518 was merged, we now have basic support for setting the server TLS.
We need:
- PKCS8 private key file (.pem)
- certificate file (.pem)

Both options were added to CLI and we require both to be present otherwise CLI will exit with an error.


#### TODO (in a subsequent PR):

- Clean up the TLS & No tls code

- Redirect HTTP requests to HTTPS? How can we do this?

Now we get an error requesting a path over HTTP: 
```
hyper::Error(
    Accept,
    TlsAcceptError(
        Custom {
            kind: InvalidData,
            error: CorruptMessage,
        },
    ),
)
```

**Comment by elpiel** [comment]
- In order to redirect http we need another port running for Sentry, so we'll just not do that at the moment
- The TLS setup was cleaned up after introducing `axum` #535
